#pragma once

#include <cstddef>
#include <type_traits>
#include <cstdint>

#include "OffsetCalculator.hpp"
#include "IMappedRegion.hpp"

namespace mapped_object
{
    template <typename FirstT = int32_t>
    class MappedObjectImpl
    {
    public:
        MappedObjectImpl(size_t object_index) : object_index(object_index)
        {
            if (!mapped_region)
            {
                throw std::logic_error("mapped_region not set for this template type");
            }

            if (object_index > std::numeric_limits<uint16_t>::max())
            {
                throw std::overflow_error("object_index would overflow uint16_t");
            }
        }
        static void set_mapped_region(IMappedRegion *region)
        {
            mapped_region = region;
            total_window_size = offset::config::window_size;
        }

        static constexpr size_t get_total_data_size_jump()
        {
            return total_data_size_jump;
        }

        std::uint16_t object_index = 0;
        // inline to share amongst translation units, alternative is to define in cpp
        static inline IMappedRegion *mapped_region = nullptr;

        using T1 = FirstT;
        using T2 = int16_t;
        using T3 = int8_t;
        static constexpr size_t total_data_size_jump = sizeof(T1) + sizeof(T2) + sizeof(T3); // 4 + 2 + 1

        static inline size_t total_window_size = offset::config::window_size;

        template <typename T, size_t data_holder_offset = 0>
        struct Accessor : private offset::OffsetCalculator<T, total_data_size_jump, data_holder_offset>
        {
            using underlying_type = T;
            std::uint16_t current_element_index = 0;
            std::uint16_t current_window_index = 0;

            size_t get_object_index() const
            {
                // Calculate the parent MappedObject address from this Accessor's address
                const char *this_addr = reinterpret_cast<const char *>(this);
                size_t accessor_offset = 0;

                // Determine which accessor this is based on data_holder_offset
                if constexpr (data_holder_offset == 0)
                    accessor_offset = offsetof(MappedObjectImpl, data1);
                else if constexpr (data_holder_offset == sizeof(T1))
                    accessor_offset = offsetof(MappedObjectImpl, data2);
                else if constexpr (data_holder_offset == sizeof(T1) + sizeof(T2))
                    accessor_offset = offsetof(MappedObjectImpl, data3);

                const char *parent_addr = this_addr - accessor_offset;
                const MappedObjectImpl *parent = reinterpret_cast<const MappedObjectImpl *>(parent_addr);
                return parent->object_index;
            }

            template <typename U>
            void push_back(U value);

            T &operator[](size_t index);
            const T &operator[](size_t index) const;

            template <bool IsConst>
            struct IteratorImpl
            {
                using AccessorType = std::conditional_t<IsConst, const Accessor, Accessor>;
                using ReferenceType = std::conditional_t<IsConst, const T &, T &>;

                AccessorType *accessor;
                size_t index;

                ReferenceType operator*() const { return (*accessor)[index]; }

                IteratorImpl &operator++()
                {
                    ++index;
                    return *this;
                }

                bool operator==(const IteratorImpl &other) const
                {
                    return index == other.index;
                }

                bool operator!=(const IteratorImpl &other) const
                {
                    return index != other.index;
                }
            };

            using Iterator = IteratorImpl<false>;
            using ConstIterator = IteratorImpl<true>;

            Iterator begin() { return Iterator{this, 0}; }
            Iterator end() { return Iterator{this, current_element_index}; }

            ConstIterator begin() const { return ConstIterator{this, 0}; }
            ConstIterator end() const { return ConstIterator{this, current_element_index}; }
        };

        Accessor<T1, 0> data1;
        Accessor<T2, sizeof(T1)> data2;
        Accessor<T3, sizeof(T1) + sizeof(T2)> data3;
    };

    using MappedObject = MappedObjectImpl<>;
    static_assert(std::is_standard_layout<MappedObject>::value, "MappedObject must be standard layout");
    MappedObjectImpl(size_t) -> MappedObjectImpl<>; // deduction guide c++17, to avoid having to do MappedObject<> for default

}

// Definitions so new types are generated by the compiler, common explicit instantiations are in the cpp
#include "MappedObject.tpp"

// Suppress duplicate instantiation in other TUs:
extern template class mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T1, 0>;
extern template class mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T2, sizeof(mapped_object::MappedObject::T1)>;
extern template class mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T3, sizeof(mapped_object::MappedObject::T1) + sizeof(mapped_object::MappedObject::T2)>;

extern template void mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T1, 0>::push_back<int>(int);
extern template void mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T2, sizeof(mapped_object::MappedObject::T1)>::push_back<int>(int);
extern template void mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T3, sizeof(mapped_object::MappedObject::T1) + sizeof(mapped_object::MappedObject::T2)>::push_back<int>(int);

extern template void mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T1, 0>::push_back<size_t>(size_t);
extern template void mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T2, sizeof(mapped_object::MappedObject::T1)>::push_back<size_t>(size_t);
extern template void mapped_object::MappedObject::Accessor<mapped_object::MappedObject::T3, sizeof(mapped_object::MappedObject::T1) + sizeof(mapped_object::MappedObject::T2)>::push_back<size_t>(size_t);